version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: riskmanagementv2-php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - traefik
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_DATABASE=riskmanagementv2
      - DB_USERNAME=appuser
      - DB_PASSWORD=33!22!11

  nginx:
    image: nginx:1.25-alpine
    container_name: riskmanagementv2-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.riskmanagementv2.rule=Host(`riskmanagementv2.test`)"
      - "traefik.http.routers.riskmanagementv2.entrypoints=websecure"
      - "traefik.http.routers.riskmanagementv2.tls=true"
      - "traefik.http.services.riskmanagementv2.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: riskmanagementv2-redis
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    driver: bridge
