<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Fehlende Länder hinzufügen
        $missingCountries = [
            // Afrika
            ['iso_code' => 'DZ', 'iso3_code' => 'DZA', 'name_translations' => '{"de": "Algerien", "en": "Algeria"}', 'continent_id' => 1, 'currency_code' => 'DZD', 'currency_name' => 'Algerischer Dinar', 'phone_prefix' => '+213', 'lat' => 28.0339, 'lng' => 1.6596, 'population' => 44700000],
            ['iso_code' => 'AO', 'iso3_code' => 'AGO', 'name_translations' => '{"de": "Angola", "en": "Angola"}', 'continent_id' => 1, 'currency_code' => 'AOA', 'currency_name' => 'Kwanza', 'phone_prefix' => '+244', 'lat' => -11.2027, 'lng' => 17.8739, 'population' => 33938000],
            ['iso_code' => 'BJ', 'iso3_code' => 'BEN', 'name_translations' => '{"de": "Benin", "en": "Benin"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+229', 'lat' => 9.3077, 'lng' => 2.3158, 'population' => 12451000],
            ['iso_code' => 'BW', 'iso3_code' => 'BWA', 'name_translations' => '{"de": "Botswana", "en": "Botswana"}', 'continent_id' => 1, 'currency_code' => 'BWP', 'currency_name' => 'Pula', 'phone_prefix' => '+267', 'lat' => -22.3285, 'lng' => 24.6849, 'population' => 2397000],
            ['iso_code' => 'BF', 'iso3_code' => 'BFA', 'name_translations' => '{"de": "Burkina Faso", "en": "Burkina Faso"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+226', 'lat' => 12.2384, 'lng' => -1.5616, 'population' => 22100000],
            ['iso_code' => 'BI', 'iso3_code' => 'BDI', 'name_translations' => '{"de": "Burundi", "en": "Burundi"}', 'continent_id' => 1, 'currency_code' => 'BIF', 'currency_name' => 'Burundi-Franc', 'phone_prefix' => '+257', 'lat' => -3.3731, 'lng' => 29.9189, 'population' => 12551000],
            ['iso_code' => 'CM', 'iso3_code' => 'CMR', 'name_translations' => '{"de": "Kamerun", "en": "Cameroon"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+237', 'lat' => 7.3697, 'lng' => 12.3547, 'population' => 27910000],
            ['iso_code' => 'CV', 'iso3_code' => 'CPV', 'name_translations' => '{"de": "Kap Verde", "en": "Cape Verde"}', 'continent_id' => 1, 'currency_code' => 'CVE', 'currency_name' => 'Kap-Verde-Escudo', 'phone_prefix' => '+238', 'lat' => 16.5388, 'lng' => -24.0132, 'population' => 593000],
            ['iso_code' => 'CF', 'iso3_code' => 'CAF', 'name_translations' => '{"de": "Zentralafrikanische Republik", "en": "Central African Republic"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+236', 'lat' => 6.6111, 'lng' => 20.9394, 'population' => 5457000],
            ['iso_code' => 'TD', 'iso3_code' => 'TCD', 'name_translations' => '{"de": "Tschad", "en": "Chad"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+235', 'lat' => 15.4542, 'lng' => 18.7322, 'population' => 17414000],
            ['iso_code' => 'KM', 'iso3_code' => 'COM', 'name_translations' => '{"de": "Komoren", "en": "Comoros"}', 'continent_id' => 1, 'currency_code' => 'KMF', 'currency_name' => 'Komoren-Franc', 'phone_prefix' => '+269', 'lat' => -11.6455, 'lng' => 43.3333, 'population' => 907000],
            ['iso_code' => 'CG', 'iso3_code' => 'COG', 'name_translations' => '{"de": "Republik Kongo", "en": "Republic of the Congo"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+242', 'lat' => -0.2280, 'lng' => 15.8277, 'population' => 5835000],
            ['iso_code' => 'CD', 'iso3_code' => 'COD', 'name_translations' => '{"de": "Demokratische Republik Kongo", "en": "Democratic Republic of the Congo"}', 'continent_id' => 1, 'currency_code' => 'CDF', 'currency_name' => 'Kongo-Franc', 'phone_prefix' => '+243', 'lat' => -4.0383, 'lng' => 21.7587, 'population' => 99010000],
            ['iso_code' => 'CI', 'iso3_code' => 'CIV', 'name_translations' => '{"de": "Elfenbeinküste", "en": "Ivory Coast"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+225', 'lat' => 7.5399, 'lng' => -5.5471, 'population' => 28088000],
            ['iso_code' => 'DJ', 'iso3_code' => 'DJI', 'name_translations' => '{"de": "Dschibuti", "en": "Djibouti"}', 'continent_id' => 1, 'currency_code' => 'DJF', 'currency_name' => 'Dschibuti-Franc', 'phone_prefix' => '+253', 'lat' => 11.8251, 'lng' => 42.5903, 'population' => 1016000],
            ['iso_code' => 'GQ', 'iso3_code' => 'GNQ', 'name_translations' => '{"de": "Äquatorialguinea", "en": "Equatorial Guinea"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+240', 'lat' => 1.6508, 'lng' => 10.2679, 'population' => 1496000],
            ['iso_code' => 'ER', 'iso3_code' => 'ERI', 'name_translations' => '{"de": "Eritrea", "en": "Eritrea"}', 'continent_id' => 1, 'currency_code' => 'ERN', 'currency_name' => 'Nakfa', 'phone_prefix' => '+291', 'lat' => 15.1794, 'lng' => 39.7823, 'population' => 3601000],
            ['iso_code' => 'SZ', 'iso3_code' => 'SWZ', 'name_translations' => '{"de": "Eswatini", "en": "Eswatini"}', 'continent_id' => 1, 'currency_code' => 'SZL', 'currency_name' => 'Lilangeni', 'phone_prefix' => '+268', 'lat' => -26.5225, 'lng' => 31.4659, 'population' => 1192000],
            ['iso_code' => 'GA', 'iso3_code' => 'GAB', 'name_translations' => '{"de": "Gabun", "en": "Gabon"}', 'continent_id' => 1, 'currency_code' => 'XAF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+241', 'lat' => -0.8037, 'lng' => 11.6094, 'population' => 2341000],
            ['iso_code' => 'GM', 'iso3_code' => 'GMB', 'name_translations' => '{"de": "Gambia", "en": "Gambia"}', 'continent_id' => 1, 'currency_code' => 'GMD', 'currency_name' => 'Dalasi', 'phone_prefix' => '+220', 'lat' => 13.4432, 'lng' => -15.3101, 'population' => 2487000],
            ['iso_code' => 'GN', 'iso3_code' => 'GIN', 'name_translations' => '{"de": "Guinea", "en": "Guinea"}', 'continent_id' => 1, 'currency_code' => 'GNF', 'currency_name' => 'Guinea-Franc', 'phone_prefix' => '+224', 'lat' => 9.9456, 'lng' => -9.6966, 'population' => 13865000],
            ['iso_code' => 'GW', 'iso3_code' => 'GNB', 'name_translations' => '{"de": "Guinea-Bissau", "en": "Guinea-Bissau"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+245', 'lat' => 11.8037, 'lng' => -15.1804, 'population' => 2061000],
            ['iso_code' => 'LS', 'iso3_code' => 'LSO', 'name_translations' => '{"de": "Lesotho", "en": "Lesotho"}', 'continent_id' => 1, 'currency_code' => 'LSL', 'currency_name' => 'Loti', 'phone_prefix' => '+266', 'lat' => -29.6100, 'lng' => 28.2336, 'population' => 2281000],
            ['iso_code' => 'LR', 'iso3_code' => 'LBR', 'name_translations' => '{"de": "Liberia", "en": "Liberia"}', 'continent_id' => 1, 'currency_code' => 'LRD', 'currency_name' => 'Liberianischer Dollar', 'phone_prefix' => '+231', 'lat' => 6.4281, 'lng' => -9.4295, 'population' => 5302000],
            ['iso_code' => 'LY', 'iso3_code' => 'LBY', 'name_translations' => '{"de": "Libyen", "en": "Libya"}', 'continent_id' => 1, 'currency_code' => 'LYD', 'currency_name' => 'Libyscher Dinar', 'phone_prefix' => '+218', 'lat' => 26.3351, 'lng' => 17.2283, 'population' => 7040000],
            ['iso_code' => 'MG', 'iso3_code' => 'MDG', 'name_translations' => '{"de": "Madagaskar", "en": "Madagascar"}', 'continent_id' => 1, 'currency_code' => 'MGA', 'currency_name' => 'Ariary', 'phone_prefix' => '+261', 'lat' => -18.7669, 'lng' => 46.8691, 'population' => 29178000],
            ['iso_code' => 'MW', 'iso3_code' => 'MWI', 'name_translations' => '{"de": "Malawi", "en": "Malawi"}', 'continent_id' => 1, 'currency_code' => 'MWK', 'currency_name' => 'Kwacha', 'phone_prefix' => '+265', 'lat' => -13.2543, 'lng' => 34.3015, 'population' => 20405000],
            ['iso_code' => 'ML', 'iso3_code' => 'MLI', 'name_translations' => '{"de": "Mali", "en": "Mali"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+223', 'lat' => 17.5707, 'lng' => -3.9962, 'population' => 21904000],
            ['iso_code' => 'MR', 'iso3_code' => 'MRT', 'name_translations' => '{"de": "Mauretanien", "en": "Mauritania"}', 'continent_id' => 1, 'currency_code' => 'MRU', 'currency_name' => 'Ouguiya', 'phone_prefix' => '+222', 'lat' => 21.0079, 'lng' => -10.9408, 'population' => 4901000],
            ['iso_code' => 'MU', 'iso3_code' => 'MUS', 'name_translations' => '{"de": "Mauritius", "en": "Mauritius"}', 'continent_id' => 1, 'currency_code' => 'MUR', 'currency_name' => 'Mauritius-Rupie', 'phone_prefix' => '+230', 'lat' => -20.3484, 'lng' => 57.5522, 'population' => 1299000],
            ['iso_code' => 'MZ', 'iso3_code' => 'MOZ', 'name_translations' => '{"de": "Mosambik", "en": "Mozambique"}', 'continent_id' => 1, 'currency_code' => 'MZN', 'currency_name' => 'Metical', 'phone_prefix' => '+258', 'lat' => -18.6657, 'lng' => 35.5296, 'population' => 32077000],
            ['iso_code' => 'NA', 'iso3_code' => 'NAM', 'name_translations' => '{"de": "Namibia", "en": "Namibia"}', 'continent_id' => 1, 'currency_code' => 'NAD', 'currency_name' => 'Namibia-Dollar', 'phone_prefix' => '+264', 'lat' => -22.9576, 'lng' => 18.4904, 'population' => 2587000],
            ['iso_code' => 'NE', 'iso3_code' => 'NER', 'name_translations' => '{"de": "Niger", "en": "Niger"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+227', 'lat' => 17.6078, 'lng' => 8.0817, 'population' => 25252000],
            ['iso_code' => 'RW', 'iso3_code' => 'RWA', 'name_translations' => '{"de": "Ruanda", "en": "Rwanda"}', 'continent_id' => 1, 'currency_code' => 'RWF', 'currency_name' => 'Ruanda-Franc', 'phone_prefix' => '+250', 'lat' => -1.9403, 'lng' => 29.8739, 'population' => 13462000],
            ['iso_code' => 'ST', 'iso3_code' => 'STP', 'name_translations' => '{"de": "São Tomé und Príncipe", "en": "São Tomé and Príncipe"}', 'continent_id' => 1, 'currency_code' => 'STN', 'currency_name' => 'Dobra', 'phone_prefix' => '+239', 'lat' => 0.1864, 'lng' => 6.6131, 'population' => 223000],
            ['iso_code' => 'SN', 'iso3_code' => 'SEN', 'name_translations' => '{"de": "Senegal", "en": "Senegal"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+221', 'lat' => 14.4974, 'lng' => -14.4524, 'population' => 17653000],
            ['iso_code' => 'SC', 'iso3_code' => 'SYC', 'name_translations' => '{"de": "Seychellen", "en": "Seychelles"}', 'continent_id' => 1, 'currency_code' => 'SCR', 'currency_name' => 'Seychellen-Rupie', 'phone_prefix' => '+248', 'lat' => -4.6796, 'lng' => 55.4920, 'population' => 99000],
            ['iso_code' => 'SL', 'iso3_code' => 'SLE', 'name_translations' => '{"de": "Sierra Leone", "en": "Sierra Leone"}', 'continent_id' => 1, 'currency_code' => 'SLE', 'currency_name' => 'Leone', 'phone_prefix' => '+232', 'lat' => 8.4606, 'lng' => -11.7799, 'population' => 8421000],
            ['iso_code' => 'SO', 'iso3_code' => 'SOM', 'name_translations' => '{"de": "Somalia", "en": "Somalia"}', 'continent_id' => 1, 'currency_code' => 'SOS', 'currency_name' => 'Somalia-Schilling', 'phone_prefix' => '+252', 'lat' => 5.1521, 'lng' => 46.1996, 'population' => 17597000],
            ['iso_code' => 'SS', 'iso3_code' => 'SSD', 'name_translations' => '{"de": "Südsudan", "en": "South Sudan"}', 'continent_id' => 1, 'currency_code' => 'SSP', 'currency_name' => 'Südsudanesisches Pfund', 'phone_prefix' => '+211', 'lat' => 6.8770, 'lng' => 31.3070, 'population' => 11381000],
            ['iso_code' => 'SD', 'iso3_code' => 'SDN', 'name_translations' => '{"de": "Sudan", "en": "Sudan"}', 'continent_id' => 1, 'currency_code' => 'SDG', 'currency_name' => 'Sudanesisches Pfund', 'phone_prefix' => '+249', 'lat' => 12.8628, 'lng' => 30.2176, 'population' => 46874000],
            ['iso_code' => 'TZ', 'iso3_code' => 'TZA', 'name_translations' => '{"de": "Tansania", "en": "Tanzania"}', 'continent_id' => 1, 'currency_code' => 'TZS', 'currency_name' => 'Tansania-Schilling', 'phone_prefix' => '+255', 'lat' => -6.3690, 'lng' => 34.8888, 'population' => 61741000],
            ['iso_code' => 'TG', 'iso3_code' => 'TGO', 'name_translations' => '{"de": "Togo", "en": "Togo"}', 'continent_id' => 1, 'currency_code' => 'XOF', 'currency_name' => 'CFA-Franc', 'phone_prefix' => '+228', 'lat' => 8.6195, 'lng' => 0.8248, 'population' => 8478000],
            ['iso_code' => 'TN', 'iso3_code' => 'TUN', 'name_translations' => '{"de": "Tunesien", "en": "Tunisia"}', 'continent_id' => 1, 'currency_code' => 'TND', 'currency_name' => 'Tunesischer Dinar', 'phone_prefix' => '+216', 'lat' => 33.8869, 'lng' => 9.5375, 'population' => 12046000],
            ['iso_code' => 'UG', 'iso3_code' => 'UGA', 'name_translations' => '{"de": "Uganda", "en": "Uganda"}', 'continent_id' => 1, 'currency_code' => 'UGX', 'currency_name' => 'Uganda-Schilling', 'phone_prefix' => '+256', 'lat' => 1.3733, 'lng' => 32.2903, 'population' => 47249000],
            ['iso_code' => 'ZM', 'iso3_code' => 'ZMB', 'name_translations' => '{"de": "Sambia", "en": "Zambia"}', 'continent_id' => 1, 'currency_code' => 'ZMW', 'currency_name' => 'Kwacha', 'phone_prefix' => '+260', 'lat' => -13.1339, 'lng' => 27.8493, 'population' => 19077000],
            ['iso_code' => 'ZW', 'iso3_code' => 'ZWE', 'name_translations' => '{"de": "Simbabwe", "en": "Zimbabwe"}', 'continent_id' => 1, 'currency_code' => 'ZWL', 'currency_name' => 'Simbabwe-Dollar', 'phone_prefix' => '+263', 'lat' => -19.0154, 'lng' => 29.1549, 'population' => 15993000],

            // Asien
            ['iso_code' => 'BH', 'iso3_code' => 'BHR', 'name_translations' => '{"de": "Bahrain", "en": "Bahrain"}', 'continent_id' => 2, 'currency_code' => 'BHD', 'currency_name' => 'Bahrain-Dinar', 'phone_prefix' => '+973', 'lat' => 26.0667, 'lng' => 50.5577, 'population' => 1748000],
            ['iso_code' => 'BT', 'iso3_code' => 'BTN', 'name_translations' => '{"de": "Bhutan", "en": "Bhutan"}', 'continent_id' => 2, 'currency_code' => 'BTN', 'currency_name' => 'Ngultrum', 'phone_prefix' => '+975', 'lat' => 27.5142, 'lng' => 90.4336, 'population' => 783000],
            ['iso_code' => 'BN', 'iso3_code' => 'BRN', 'name_translations' => '{"de": "Brunei", "en": "Brunei"}', 'continent_id' => 2, 'currency_code' => 'BND', 'currency_name' => 'Brunei-Dollar', 'phone_prefix' => '+673', 'lat' => 4.5353, 'lng' => 114.7277, 'population' => 449000],
            ['iso_code' => 'KH', 'iso3_code' => 'KHM', 'name_translations' => '{"de": "Kambodscha", "en": "Cambodia"}', 'continent_id' => 2, 'currency_code' => 'KHR', 'currency_name' => 'Riel', 'phone_prefix' => '+855', 'lat' => 12.5657, 'lng' => 104.9910, 'population' => 16767000],
            ['iso_code' => 'JP', 'iso3_code' => 'JPN', 'name_translations' => '{"de": "Japan", "en": "Japan"}', 'continent_id' => 2, 'currency_code' => 'JPY', 'currency_name' => 'Yen', 'phone_prefix' => '+81', 'lat' => 36.2048, 'lng' => 138.2529, 'population' => 125800000],
            ['iso_code' => 'JO', 'iso3_code' => 'JOR', 'name_translations' => '{"de": "Jordanien", "en": "Jordan"}', 'continent_id' => 2, 'currency_code' => 'JOD', 'currency_name' => 'Jordanischer Dinar', 'phone_prefix' => '+962', 'lat' => 30.5852, 'lng' => 36.2384, 'population' => 10300000],
            ['iso_code' => 'KP', 'iso3_code' => 'PRK', 'name_translations' => '{"de": "Nordkorea", "en": "North Korea"}', 'continent_id' => 2, 'currency_code' => 'KPW', 'currency_name' => 'Won', 'phone_prefix' => '+850', 'lat' => 40.3399, 'lng' => 127.5101, 'population' => 25800000],
            ['iso_code' => 'KW', 'iso3_code' => 'KWT', 'name_translations' => '{"de": "Kuwait", "en": "Kuwait"}', 'continent_id' => 2, 'currency_code' => 'KWD', 'currency_name' => 'Kuwait-Dinar', 'phone_prefix' => '+965', 'lat' => 29.3117, 'lng' => 47.4818, 'population' => 4329000],
            ['iso_code' => 'LA', 'iso3_code' => 'LAO', 'name_translations' => '{"de": "Laos", "en": "Laos"}', 'continent_id' => 2, 'currency_code' => 'LAK', 'currency_name' => 'Kip', 'phone_prefix' => '+856', 'lat' => 19.8563, 'lng' => 102.4955, 'population' => 7529000],
            ['iso_code' => 'LB', 'iso3_code' => 'LBN', 'name_translations' => '{"de": "Libanon", "en": "Lebanon"}', 'continent_id' => 2, 'currency_code' => 'LBP', 'currency_name' => 'Libanesisches Pfund', 'phone_prefix' => '+961', 'lat' => 33.8547, 'lng' => 35.8623, 'population' => 6825000],
            ['iso_code' => 'MY', 'iso3_code' => 'MYS', 'name_translations' => '{"de": "Malaysia", "en": "Malaysia"}', 'continent_id' => 2, 'currency_code' => 'MYR', 'currency_name' => 'Ringgit', 'phone_prefix' => '+60', 'lat' => 4.2105, 'lng' => 101.9758, 'population' => 33938000],
            ['iso_code' => 'MV', 'iso3_code' => 'MDV', 'name_translations' => '{"de": "Malediven", "en": "Maldives"}', 'continent_id' => 2, 'currency_code' => 'MVR', 'currency_name' => 'Rufiyaa', 'phone_prefix' => '+960', 'lat' => 3.2028, 'lng' => 73.2207, 'population' => 540000],
            ['iso_code' => 'OM', 'iso3_code' => 'OMN', 'name_translations' => '{"de": "Oman", "en": "Oman"}', 'continent_id' => 2, 'currency_code' => 'OMR', 'currency_name' => 'Rial', 'phone_prefix' => '+968', 'lat' => 21.4735, 'lng' => 55.9754, 'population' => 5223000],
            ['iso_code' => 'PH', 'iso3_code' => 'PHL', 'name_translations' => '{"de": "Philippinen", "en": "Philippines"}', 'continent_id' => 2, 'currency_code' => 'PHP', 'currency_name' => 'Peso', 'phone_prefix' => '+63', 'lat' => 12.8797, 'lng' => 121.7740, 'population' => 111046000],
            ['iso_code' => 'QA', 'iso3_code' => 'QAT', 'name_translations' => '{"de": "Katar", "en": "Qatar"}', 'continent_id' => 2, 'currency_code' => 'QAR', 'currency_name' => 'Riyal', 'phone_prefix' => '+974', 'lat' => 25.3548, 'lng' => 51.1839, 'population' => 2881000],
            ['iso_code' => 'SG', 'iso3_code' => 'SGP', 'name_translations' => '{"de": "Singapur", "en": "Singapore"}', 'continent_id' => 2, 'currency_code' => 'SGD', 'currency_name' => 'Singapur-Dollar', 'phone_prefix' => '+65', 'lat' => 1.3521, 'lng' => 103.8198, 'population' => 5896000],
            ['iso_code' => 'LK', 'iso3_code' => 'LKA', 'name_translations' => '{"de": "Sri Lanka", "en": "Sri Lanka"}', 'continent_id' => 2, 'currency_code' => 'LKR', 'currency_name' => 'Sri-Lanka-Rupie', 'phone_prefix' => '+94', 'lat' => 7.8731, 'lng' => 80.7718, 'population' => 22157000],
            ['iso_code' => 'TH', 'iso3_code' => 'THA', 'name_translations' => '{"de": "Thailand", "en": "Thailand"}', 'continent_id' => 2, 'currency_code' => 'THB', 'currency_name' => 'Baht', 'phone_prefix' => '+66', 'lat' => 15.8700, 'lng' => 100.9925, 'population' => 70078000],
            ['iso_code' => 'TL', 'iso3_code' => 'TLS', 'name_translations' => '{"de": "Osttimor", "en": "Timor-Leste"}', 'continent_id' => 2, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+670', 'lat' => -8.8742, 'lng' => 125.7275, 'population' => 1341000],
            ['iso_code' => 'AE', 'iso3_code' => 'ARE', 'name_translations' => '{"de": "Vereinigte Arabische Emirate", "en": "United Arab Emirates"}', 'continent_id' => 2, 'currency_code' => 'AED', 'currency_name' => 'Dirham', 'phone_prefix' => '+971', 'lat' => 23.4241, 'lng' => 53.8478, 'population' => 9991000],
            ['iso_code' => 'VN', 'iso3_code' => 'VNM', 'name_translations' => '{"de": "Vietnam", "en": "Vietnam"}', 'continent_id' => 2, 'currency_code' => 'VND', 'currency_name' => 'Dong', 'phone_prefix' => '+84', 'lat' => 14.0583, 'lng' => 108.2772, 'population' => 98186000],

            // Europa
            ['iso_code' => 'AD', 'iso3_code' => 'AND', 'name_translations' => '{"de": "Andorra", "en": "Andorra"}', 'continent_id' => 3, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+376', 'lat' => 42.5063, 'lng' => 1.5218, 'population' => 79000],
            ['iso_code' => 'BY', 'iso3_code' => 'BLR', 'name_translations' => '{"de": "Belarus", "en": "Belarus"}', 'continent_id' => 3, 'currency_code' => 'BYN', 'currency_name' => 'Rubel', 'phone_prefix' => '+375', 'lat' => 53.7098, 'lng' => 27.9534, 'population' => 9449000],
            ['iso_code' => 'FO', 'iso3_code' => 'FRO', 'name_translations' => '{"de": "Färöer", "en": "Faroe Islands"}', 'continent_id' => 3, 'currency_code' => 'DKK', 'currency_name' => 'Dänische Krone', 'phone_prefix' => '+298', 'lat' => 61.8926, 'lng' => -6.9118, 'population' => 53000],
            ['iso_code' => 'GI', 'iso3_code' => 'GIB', 'name_translations' => '{"de": "Gibraltar", "en": "Gibraltar"}', 'continent_id' => 3, 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar-Pfund', 'phone_prefix' => '+350', 'lat' => 36.1408, 'lng' => -5.3536, 'population' => 34000],
            ['iso_code' => 'GG', 'iso3_code' => 'GGY', 'name_translations' => '{"de": "Guernsey", "en": "Guernsey"}', 'continent_id' => 3, 'currency_code' => 'GBP', 'currency_name' => 'Pfund Sterling', 'phone_prefix' => '+44', 'lat' => 49.4658, 'lng' => -2.5854, 'population' => 63000],
            ['iso_code' => 'IM', 'iso3_code' => 'IMN', 'name_translations' => '{"de": "Isle of Man", "en": "Isle of Man"}', 'continent_id' => 3, 'currency_code' => 'IMP', 'currency_name' => 'Isle of Man Pfund', 'phone_prefix' => '+44', 'lat' => 54.2361, 'lng' => -4.5481, 'population' => 85000],
            ['iso_code' => 'JE', 'iso3_code' => 'JEY', 'name_translations' => '{"de": "Jersey", "en": "Jersey"}', 'continent_id' => 3, 'currency_code' => 'JEP', 'currency_name' => 'Jersey-Pfund', 'phone_prefix' => '+44', 'lat' => 49.2144, 'lng' => -2.1312, 'population' => 106000],
            ['iso_code' => 'XK', 'iso3_code' => 'XKX', 'name_translations' => '{"de": "Kosovo", "en": "Kosovo"}', 'continent_id' => 3, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+383', 'lat' => 42.6026, 'lng' => 20.9030, 'population' => 1873000],
            ['iso_code' => 'LI', 'iso3_code' => 'LIE', 'name_translations' => '{"de": "Liechtenstein", "en": "Liechtenstein"}', 'continent_id' => 3, 'currency_code' => 'CHF', 'currency_name' => 'Schweizer Franken', 'phone_prefix' => '+423', 'lat' => 47.1660, 'lng' => 9.5554, 'population' => 39000],
            ['iso_code' => 'MC', 'iso3_code' => 'MCO', 'name_translations' => '{"de": "Monaco", "en": "Monaco"}', 'continent_id' => 3, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+377', 'lat' => 43.7384, 'lng' => 7.4246, 'population' => 39000],
            ['iso_code' => 'SM', 'iso3_code' => 'SMR', 'name_translations' => '{"de": "San Marino", "en": "San Marino"}', 'continent_id' => 3, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+378', 'lat' => 43.9424, 'lng' => 12.4578, 'population' => 34000],
            ['iso_code' => 'SJ', 'iso3_code' => 'SJM', 'name_translations' => '{"de": "Spitzbergen und Jan Mayen", "en": "Svalbard and Jan Mayen"}', 'continent_id' => 3, 'currency_code' => 'NOK', 'currency_name' => 'Norwegische Krone', 'phone_prefix' => '+47', 'lat' => 77.5536, 'lng' => 23.6702, 'population' => 3000],
            ['iso_code' => 'VA', 'iso3_code' => 'VAT', 'name_translations' => '{"de": "Vatikanstadt", "en": "Vatican City"}', 'continent_id' => 3, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+379', 'lat' => 41.9029, 'lng' => 12.4534, 'population' => 800],

            // Nordamerika
            ['iso_code' => 'AI', 'iso3_code' => 'AIA', 'name_translations' => '{"de": "Anguilla", "en": "Anguilla"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1264', 'lat' => 18.2206, 'lng' => -63.0686, 'population' => 15000],
            ['iso_code' => 'AG', 'iso3_code' => 'ATG', 'name_translations' => '{"de": "Antigua und Barbuda", "en": "Antigua and Barbuda"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1268', 'lat' => 17.0608, 'lng' => -61.7964, 'population' => 99000],
            ['iso_code' => 'AW', 'iso3_code' => 'ABW', 'name_translations' => '{"de": "Aruba", "en": "Aruba"}', 'continent_id' => 5, 'currency_code' => 'AWG', 'currency_name' => 'Aruba-Florin', 'phone_prefix' => '+297', 'lat' => 12.5211, 'lng' => -69.9683, 'population' => 107000],
            ['iso_code' => 'BS', 'iso3_code' => 'BHS', 'name_translations' => '{"de": "Bahamas", "en": "Bahamas"}', 'continent_id' => 5, 'currency_code' => 'BSD', 'currency_name' => 'Bahama-Dollar', 'phone_prefix' => '+1242', 'lat' => 25.0343, 'lng' => -77.3963, 'population' => 396000],
            ['iso_code' => 'BB', 'iso3_code' => 'BRB', 'name_translations' => '{"de": "Barbados", "en": "Barbados"}', 'continent_id' => 5, 'currency_code' => 'BBD', 'currency_name' => 'Barbados-Dollar', 'phone_prefix' => '+1246', 'lat' => 13.1939, 'lng' => -59.5432, 'population' => 288000],
            ['iso_code' => 'BZ', 'iso3_code' => 'BLZ', 'name_translations' => '{"de": "Belize", "en": "Belize"}', 'continent_id' => 5, 'currency_code' => 'BZD', 'currency_name' => 'Belize-Dollar', 'phone_prefix' => '+501', 'lat' => 17.1899, 'lng' => -88.4976, 'population' => 405000],
            ['iso_code' => 'BM', 'iso3_code' => 'BMU', 'name_translations' => '{"de": "Bermuda", "en": "Bermuda"}', 'continent_id' => 5, 'currency_code' => 'BMD', 'currency_name' => 'Bermuda-Dollar', 'phone_prefix' => '+1441', 'lat' => 32.3078, 'lng' => -64.7505, 'population' => 64000],
            ['iso_code' => 'VG', 'iso3_code' => 'VGB', 'name_translations' => '{"de": "Britische Jungferninseln", "en": "British Virgin Islands"}', 'continent_id' => 5, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1284', 'lat' => 18.4207, 'lng' => -64.6399, 'population' => 31000],
            ['iso_code' => 'KY', 'iso3_code' => 'CYM', 'name_translations' => '{"de": "Kaimaninseln", "en": "Cayman Islands"}', 'continent_id' => 5, 'currency_code' => 'KYD', 'currency_name' => 'Kaiman-Dollar', 'phone_prefix' => '+1345', 'lat' => 19.3133, 'lng' => -81.2546, 'population' => 68000],
            ['iso_code' => 'CU', 'iso3_code' => 'CUB', 'name_translations' => '{"de": "Kuba", "en": "Cuba"}', 'continent_id' => 5, 'currency_code' => 'CUP', 'currency_name' => 'Kubanischer Peso', 'phone_prefix' => '+53', 'lat' => 21.5218, 'lng' => -77.7812, 'population' => 11317000],
            ['iso_code' => 'CW', 'iso3_code' => 'CUW', 'name_translations' => '{"de": "Curaçao", "en": "Curaçao"}', 'continent_id' => 5, 'currency_code' => 'ANG', 'currency_name' => 'Niederländischer Antillen-Gulden', 'phone_prefix' => '+599', 'lat' => 12.1696, 'lng' => -68.9900, 'population' => 164000],
            ['iso_code' => 'DM', 'iso3_code' => 'DMA', 'name_translations' => '{"de": "Dominica", "en": "Dominica"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1767', 'lat' => 15.4150, 'lng' => -61.3710, 'population' => 72000],
            ['iso_code' => 'DO', 'iso3_code' => 'DOM', 'name_translations' => '{"de": "Dominikanische Republik", "en": "Dominican Republic"}', 'continent_id' => 5, 'currency_code' => 'DOP', 'currency_name' => 'Dominikanischer Peso', 'phone_prefix' => '+1809', 'lat' => 18.7357, 'lng' => -70.1627, 'population' => 11117000],
            ['iso_code' => 'SV', 'iso3_code' => 'SLV', 'name_translations' => '{"de": "El Salvador", "en": "El Salvador"}', 'continent_id' => 5, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+503', 'lat' => 13.7942, 'lng' => -88.8965, 'population' => 6518000],
            ['iso_code' => 'GL', 'iso3_code' => 'GRL', 'name_translations' => '{"de": "Grönland", "en": "Greenland"}', 'continent_id' => 5, 'currency_code' => 'DKK', 'currency_name' => 'Dänische Krone', 'phone_prefix' => '+299', 'lat' => 71.7069, 'lng' => -42.6043, 'population' => 56000],
            ['iso_code' => 'GD', 'iso3_code' => 'GRD', 'name_translations' => '{"de": "Grenada", "en": "Grenada"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1473', 'lat' => 12.2628, 'lng' => -61.6040, 'population' => 113000],
            ['iso_code' => 'GP', 'iso3_code' => 'GLP', 'name_translations' => '{"de": "Guadeloupe", "en": "Guadeloupe"}', 'continent_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+590', 'lat' => 16.9950, 'lng' => -62.0670, 'population' => 400000],
            ['iso_code' => 'HT', 'iso3_code' => 'HTI', 'name_translations' => '{"de": "Haiti", "en": "Haiti"}', 'continent_id' => 5, 'currency_code' => 'HTG', 'currency_name' => 'Gourde', 'phone_prefix' => '+509', 'lat' => 18.9712, 'lng' => -72.2852, 'population' => 11541000],
            ['iso_code' => 'HN', 'iso3_code' => 'HND', 'name_translations' => '{"de": "Honduras", "en": "Honduras"}', 'continent_id' => 5, 'currency_code' => 'HNL', 'currency_name' => 'Lempira', 'phone_prefix' => '+504', 'lat' => 15.2000, 'lng' => -86.2419, 'population' => 10063000],
            ['iso_code' => 'JM', 'iso3_code' => 'JAM', 'name_translations' => '{"de": "Jamaika", "en": "Jamaica"}', 'continent_id' => 5, 'currency_code' => 'JMD', 'currency_name' => 'Jamaika-Dollar', 'phone_prefix' => '+1876', 'lat' => 18.1096, 'lng' => -77.2975, 'population' => 2973000],
            ['iso_code' => 'MQ', 'iso3_code' => 'MTQ', 'name_translations' => '{"de": "Martinique", "en": "Martinique"}', 'continent_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+596', 'lat' => 14.6415, 'lng' => -61.0242, 'population' => 375000],
            ['iso_code' => 'MS', 'iso3_code' => 'MSR', 'name_translations' => '{"de": "Montserrat", "en": "Montserrat"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1664', 'lat' => 16.7425, 'lng' => -62.1874, 'population' => 5000],
            ['iso_code' => 'NI', 'iso3_code' => 'NIC', 'name_translations' => '{"de": "Nicaragua", "en": "Nicaragua"}', 'continent_id' => 5, 'currency_code' => 'NIO', 'currency_name' => 'Córdoba', 'phone_prefix' => '+505', 'lat' => 12.2651, 'lng' => -85.2072, 'population' => 6851000],
            ['iso_code' => 'PA', 'iso3_code' => 'PAN', 'name_translations' => '{"de": "Panama", "en": "Panama"}', 'continent_id' => 5, 'currency_code' => 'PAB', 'currency_name' => 'Balboa', 'phone_prefix' => '+507', 'lat' => 8.5380, 'lng' => -80.7821, 'population' => 4381000],
            ['iso_code' => 'PR', 'iso3_code' => 'PRI', 'name_translations' => '{"de": "Puerto Rico", "en": "Puerto Rico"}', 'continent_id' => 5, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1787', 'lat' => 18.2208, 'lng' => -66.5901, 'population' => 3194000],
            ['iso_code' => 'BL', 'iso3_code' => 'BLM', 'name_translations' => '{"de": "Saint-Barthélemy", "en": "Saint Barthélemy"}', 'continent_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+590', 'lat' => 17.9000, 'lng' => -62.8333, 'population' => 10000],
            ['iso_code' => 'KN', 'iso3_code' => 'KNA', 'name_translations' => '{"de": "St. Kitts und Nevis", "en": "Saint Kitts and Nevis"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1869', 'lat' => 17.3578, 'lng' => -62.7830, 'population' => 53000],
            ['iso_code' => 'LC', 'iso3_code' => 'LCA', 'name_translations' => '{"de": "St. Lucia", "en": "Saint Lucia"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1758', 'lat' => 13.9094, 'lng' => -60.9789, 'population' => 184000],
            ['iso_code' => 'MF', 'iso3_code' => 'MAF', 'name_translations' => '{"de": "Saint-Martin", "en": "Saint Martin"}', 'continent_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+590', 'lat' => 18.0708, 'lng' => -63.0501, 'population' => 39000],
            ['iso_code' => 'PM', 'iso3_code' => 'SPM', 'name_translations' => '{"de": "Saint-Pierre und Miquelon", "en": "Saint Pierre and Miquelon"}', 'continent_id' => 5, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+508', 'lat' => 46.8852, 'lng' => -56.3159, 'population' => 6000],
            ['iso_code' => 'VC', 'iso3_code' => 'VCT', 'name_translations' => '{"de": "St. Vincent und die Grenadinen", "en": "Saint Vincent and the Grenadines"}', 'continent_id' => 5, 'currency_code' => 'XCD', 'currency_name' => 'Ostkaribischer Dollar', 'phone_prefix' => '+1784', 'lat' => 12.9843, 'lng' => -61.2872, 'population' => 111000],
            ['iso_code' => 'SX', 'iso3_code' => 'SXM', 'name_translations' => '{"de": "Sint Maarten", "en": "Sint Maarten"}', 'continent_id' => 5, 'currency_code' => 'ANG', 'currency_name' => 'Niederländischer Antillen-Gulden', 'phone_prefix' => '+1721', 'lat' => 18.0425, 'lng' => -63.0548, 'population' => 42000],
            ['iso_code' => 'TT', 'iso3_code' => 'TTO', 'name_translations' => '{"de": "Trinidad und Tobago", "en": "Trinidad and Tobago"}', 'continent_id' => 5, 'currency_code' => 'TTD', 'currency_name' => 'Trinidad-und-Tobago-Dollar', 'phone_prefix' => '+1868', 'lat' => 10.6918, 'lng' => -61.2225, 'population' => 1400000],
            ['iso_code' => 'TC', 'iso3_code' => 'TCA', 'name_translations' => '{"de": "Turks- und Caicosinseln", "en": "Turks and Caicos Islands"}', 'continent_id' => 5, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1649', 'lat' => 21.6940, 'lng' => -71.7979, 'population' => 39000],
            ['iso_code' => 'VI', 'iso3_code' => 'VIR', 'name_translations' => '{"de": "Amerikanische Jungferninseln", "en": "US Virgin Islands"}', 'continent_id' => 5, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1340', 'lat' => 18.3358, 'lng' => -64.8963, 'population' => 104000],

            // Südamerika
            ['iso_code' => 'BO', 'iso3_code' => 'BOL', 'name_translations' => '{"de": "Bolivien", "en": "Bolivia"}', 'continent_id' => 6, 'currency_code' => 'BOB', 'currency_name' => 'Boliviano', 'phone_prefix' => '+591', 'lat' => -16.2902, 'lng' => -63.5887, 'population' => 11832000],
            ['iso_code' => 'FK', 'iso3_code' => 'FLK', 'name_translations' => '{"de": "Falklandinseln", "en": "Falkland Islands"}', 'continent_id' => 6, 'currency_code' => 'FKP', 'currency_name' => 'Falkland-Pfund', 'phone_prefix' => '+500', 'lat' => -51.7963, 'lng' => -59.5236, 'population' => 3000],
            ['iso_code' => 'GF', 'iso3_code' => 'GUF', 'name_translations' => '{"de": "Französisch-Guayana", "en": "French Guiana"}', 'continent_id' => 6, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'phone_prefix' => '+594', 'lat' => 3.9339, 'lng' => -53.1258, 'population' => 299000],
            ['iso_code' => 'GY', 'iso3_code' => 'GUY', 'name_translations' => '{"de": "Guyana", "en": "Guyana"}', 'continent_id' => 6, 'currency_code' => 'GYD', 'currency_name' => 'Guyana-Dollar', 'phone_prefix' => '+592', 'lat' => 4.8604, 'lng' => -58.9302, 'population' => 787000],
            ['iso_code' => 'PY', 'iso3_code' => 'PRY', 'name_translations' => '{"de": "Paraguay", "en": "Paraguay"}', 'continent_id' => 6, 'currency_code' => 'PYG', 'currency_name' => 'Guaraní', 'phone_prefix' => '+595', 'lat' => -23.4425, 'lng' => -58.4438, 'population' => 7219000],
            ['iso_code' => 'SR', 'iso3_code' => 'SUR', 'name_translations' => '{"de": "Suriname", "en": "Suriname"}', 'continent_id' => 6, 'currency_code' => 'SRD', 'currency_name' => 'Suriname-Dollar', 'phone_prefix' => '+597', 'lat' => 3.9193, 'lng' => -56.0278, 'population' => 587000],
            ['iso_code' => 'UY', 'iso3_code' => 'URY', 'name_translations' => '{"de": "Uruguay", "en": "Uruguay"}', 'continent_id' => 6, 'currency_code' => 'UYU', 'currency_name' => 'Uruguayischer Peso', 'phone_prefix' => '+598', 'lat' => -32.5228, 'lng' => -55.7658, 'population' => 3518000],

            // Ozeanien
            ['iso_code' => 'AS', 'iso3_code' => 'ASM', 'name_translations' => '{"de": "Amerikanisch-Samoa", "en": "American Samoa"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1684', 'lat' => -14.2710, 'lng' => -170.1322, 'population' => 55000],
            ['iso_code' => 'CK', 'iso3_code' => 'COK', 'name_translations' => '{"de": "Cookinseln", "en": "Cook Islands"}', 'continent_id' => 7, 'currency_code' => 'NZD', 'currency_name' => 'Neuseeland-Dollar', 'phone_prefix' => '+682', 'lat' => -21.2367, 'lng' => -159.7777, 'population' => 18000],
            ['iso_code' => 'FJ', 'iso3_code' => 'FJI', 'name_translations' => '{"de": "Fidschi", "en": "Fiji"}', 'continent_id' => 7, 'currency_code' => 'FJD', 'currency_name' => 'Fidschi-Dollar', 'phone_prefix' => '+679', 'lat' => -16.5787, 'lng' => 179.4140, 'population' => 924000],
            ['iso_code' => 'PF', 'iso3_code' => 'PYF', 'name_translations' => '{"de": "Französisch-Polynesien", "en": "French Polynesia"}', 'continent_id' => 7, 'currency_code' => 'XPF', 'currency_name' => 'CFP-Franc', 'phone_prefix' => '+689', 'lat' => -17.6797, 'lng' => -149.4068, 'population' => 281000],
            ['iso_code' => 'GU', 'iso3_code' => 'GUM', 'name_translations' => '{"de": "Guam", "en": "Guam"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1671', 'lat' => 13.4443, 'lng' => 144.7937, 'population' => 170000],
            ['iso_code' => 'KI', 'iso3_code' => 'KIR', 'name_translations' => '{"de": "Kiribati", "en": "Kiribati"}', 'continent_id' => 7, 'currency_code' => 'AUD', 'currency_name' => 'Australischer Dollar', 'phone_prefix' => '+686', 'lat' => -3.3704, 'lng' => -168.7340, 'population' => 123000],
            ['iso_code' => 'MH', 'iso3_code' => 'MHL', 'name_translations' => '{"de": "Marshallinseln", "en": "Marshall Islands"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+692', 'lat' => 7.1315, 'lng' => 171.1845, 'population' => 60000],
            ['iso_code' => 'FM', 'iso3_code' => 'FSM', 'name_translations' => '{"de": "Mikronesien", "en": "Micronesia"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+691', 'lat' => 7.4256, 'lng' => 150.5508, 'population' => 116000],
            ['iso_code' => 'NR', 'iso3_code' => 'NRU', 'name_translations' => '{"de": "Nauru", "en": "Nauru"}', 'continent_id' => 7, 'currency_code' => 'AUD', 'currency_name' => 'Australischer Dollar', 'phone_prefix' => '+674', 'lat' => -0.5228, 'lng' => 166.9315, 'population' => 11000],
            ['iso_code' => 'NC', 'iso3_code' => 'NCL', 'name_translations' => '{"de": "Neukaledonien", "en": "New Caledonia"}', 'continent_id' => 7, 'currency_code' => 'XPF', 'currency_name' => 'CFP-Franc', 'phone_prefix' => '+687', 'lat' => -20.9043, 'lng' => 165.6180, 'population' => 290000],
            ['iso_code' => 'NU', 'iso3_code' => 'NIU', 'name_translations' => '{"de": "Niue", "en": "Niue"}', 'continent_id' => 7, 'currency_code' => 'NZD', 'currency_name' => 'Neuseeland-Dollar', 'phone_prefix' => '+683', 'lat' => -19.0544, 'lng' => -169.8672, 'population' => 2000],
            ['iso_code' => 'NF', 'iso3_code' => 'NFK', 'name_translations' => '{"de": "Norfolkinsel", "en": "Norfolk Island"}', 'continent_id' => 7, 'currency_code' => 'AUD', 'currency_name' => 'Australischer Dollar', 'phone_prefix' => '+672', 'lat' => -29.0408, 'lng' => 167.9547, 'population' => 2000],
            ['iso_code' => 'MP', 'iso3_code' => 'MNP', 'name_translations' => '{"de": "Nördliche Marianen", "en": "Northern Mariana Islands"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+1670', 'lat' => 17.3308, 'lng' => 145.3846, 'population' => 58000],
            ['iso_code' => 'PW', 'iso3_code' => 'PLW', 'name_translations' => '{"de": "Palau", "en": "Palau"}', 'continent_id' => 7, 'currency_code' => 'USD', 'currency_name' => 'US-Dollar', 'phone_prefix' => '+680', 'lat' => 7.5150, 'lng' => 134.5825, 'population' => 18000],
            ['iso_code' => 'PG', 'iso3_code' => 'PNG', 'name_translations' => '{"de": "Papua-Neuguinea", "en": "Papua New Guinea"}', 'continent_id' => 7, 'currency_code' => 'PGK', 'currency_name' => 'Kina', 'phone_prefix' => '+675', 'lat' => -6.3149, 'lng' => 143.9555, 'population' => 9119000],
            ['iso_code' => 'PN', 'iso3_code' => 'PCN', 'name_translations' => '{"de": "Pitcairninseln", "en": "Pitcairn Islands"}', 'continent_id' => 7, 'currency_code' => 'NZD', 'currency_name' => 'Neuseeland-Dollar', 'phone_prefix' => '+64', 'lat' => -24.7036, 'lng' => -127.4393, 'population' => 50],
            ['iso_code' => 'WS', 'iso3_code' => 'WSM', 'name_translations' => '{"de": "Samoa", "en": "Samoa"}', 'continent_id' => 7, 'currency_code' => 'WST', 'currency_name' => 'Tala', 'phone_prefix' => '+685', 'lat' => -13.7590, 'lng' => -172.1046, 'population' => 200000],
            ['iso_code' => 'SB', 'iso3_code' => 'SLB', 'name_translations' => '{"de": "Salomonen", "en": "Solomon Islands"}', 'continent_id' => 7, 'currency_code' => 'SBD', 'currency_name' => 'Salomonen-Dollar', 'phone_prefix' => '+677', 'lat' => -9.6457, 'lng' => 160.1562, 'population' => 703000],
            ['iso_code' => 'TK', 'iso3_code' => 'TKL', 'name_translations' => '{"de": "Tokelau", "en": "Tokelau"}', 'continent_id' => 7, 'currency_code' => 'NZD', 'currency_name' => 'Neuseeland-Dollar', 'phone_prefix' => '+690', 'lat' => -8.9676, 'lng' => -171.8555, 'population' => 1000],
            ['iso_code' => 'TO', 'iso3_code' => 'TON', 'name_translations' => '{"de": "Tonga", "en": "Tonga"}', 'continent_id' => 7, 'currency_code' => 'TOP', 'currency_name' => 'Pa\'anga', 'phone_prefix' => '+676', 'lat' => -21.1789, 'lng' => -175.1982, 'population' => 107000],
            ['iso_code' => 'TV', 'iso3_code' => 'TUV', 'name_translations' => '{"de": "Tuvalu", "en": "Tuvalu"}', 'continent_id' => 7, 'currency_code' => 'AUD', 'currency_name' => 'Australischer Dollar', 'phone_prefix' => '+688', 'lat' => -7.1095, 'lng' => 177.6493, 'population' => 12000],
            ['iso_code' => 'VU', 'iso3_code' => 'VUT', 'name_translations' => '{"de": "Vanuatu", "en": "Vanuatu"}', 'continent_id' => 7, 'currency_code' => 'VUV', 'currency_name' => 'Vatu', 'phone_prefix' => '+678', 'lat' => -15.3767, 'lng' => 166.9592, 'population' => 321000],
            ['iso_code' => 'WF', 'iso3_code' => 'WLF', 'name_translations' => '{"de": "Wallis und Futuna", "en": "Wallis and Futuna"}', 'continent_id' => 7, 'currency_code' => 'XPF', 'currency_name' => 'CFP-Franc', 'phone_prefix' => '+681', 'lat' => -13.7687, 'lng' => -177.1562, 'population' => 11000]
        ];

        foreach ($missingCountries as $country) {
            // Überprüfen ob das Land bereits existiert
            $exists = DB::table('countries')->where('iso_code', $country['iso_code'])->exists();
            if (!$exists) {
                DB::table('countries')->insert(array_merge($country, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Die hinzugefügten Länder wieder entfernen
        $addedCountryCodes = [
            'DZ', 'AO', 'BJ', 'BW', 'BF', 'BI', 'CM', 'CV', 'CF', 'TD', 'KM', 'CG', 'CD', 'CI', 'DJ', 'GQ', 'ER', 'SZ', 'GA', 'GM', 'GN', 'GW', 'LS', 'LR', 'LY', 'MG', 'MW', 'ML', 'MR', 'MU', 'MZ', 'NA', 'NE', 'RW', 'ST', 'SN', 'SC', 'SL', 'SO', 'SS', 'SD', 'TZ', 'TG', 'TN', 'UG', 'ZM', 'ZW',
            'AE', 'FO', 'GI', 'GG', 'IM', 'JE', 'XK', 'SJ',
            'AI', 'AG', 'AW', 'BS', 'BB', 'BZ', 'BM', 'VG', 'KY', 'CU', 'CW', 'DM', 'DO', 'SV', 'GL', 'GD', 'GP', 'HT', 'HN', 'JM', 'MQ', 'MS', 'NI', 'PA', 'PR', 'BL', 'KN', 'LC', 'MF', 'PM', 'VC', 'SX', 'TT', 'TC', 'VI',
            'BO', 'FK', 'GF', 'GY', 'PY', 'SR', 'UY',
            'AS', 'CK', 'PF', 'GU', 'KI', 'MH', 'FM', 'NR', 'NC', 'NU', 'NF', 'MP', 'PW', 'PN', 'WS', 'SB', 'TK', 'TO', 'TV', 'VU', 'WF'
        ];
        
        DB::table('countries')->whereIn('iso_code', $addedCountryCodes)->delete();
    }
};
